### ISSUE TITLE
使用`custom-dailynote-yyyyMMdd`属性查找日记

### ISSUE THREAD

**Issue by InEase** [Wetoria/sy-plugin-enhance#1]
作者您好！这个插件太棒了！实现了很多我之前一直想要的功能，特别是文档尾部的反链面板 && 翻日记的快捷键，不过目前查找日记只支持 `/daily note/` 文件夹下的，文档名称为 `yyyy-MM-dd` 格式的日记，思源在`2.11.1`版本(siyuan-note/siyuan#9807)引入了`custom-dailynote-yyyyMMdd`属性，作者大大有考虑支持吗～我可以提一个pr～

**Comment by Wetoria** [comment]
fixed #398a83f
