### ISSUE TITLE
重启插件后，「底部反链」的显示问题

### ISSUE THREAD

**Issue by QMike0** [Wetoria/sy-plugin-enhance#11]
文档底部反链的正常显示如下：
![image](https://github.com/Wetoria/sy-plugin-enhance/assets/43239563/e321dec9-ff99-4d64-9a36-729d1007283b)

然而当关闭再重启插件后，底部反链就会变成如下情况，必须关闭再重新打开该文档后才能恢复正常显示：
![image](https://github.com/Wetoria/sy-plugin-enhance/assets/43239563/4b4fdff8-f801-4ac5-983a-ef850f824e4b)

应该属于底部反链的一个加载bug

另外佬是否可以为`启用/关闭底部反链`添加一个快捷键。因为感觉并不是每个文档下面都需要立刻显示出它的反链是什么，假如有快捷键就可以快速切换相应的模式

PS：
顺便催更一下[这个issue](https://github.com/Wetoria/sy-plugin-enhance/issues/9)
佬快更新插件，秋梨膏！

**Comment by Wetoria** [comment]
应该是数据没刷新导致的，目前只有在文档加载的时候，才会获取反链数据。

实际上我考虑过增加刷新功能，但是一直没实现。由于精力问题，后续逐步推进，见谅。

issue我先关了。后续可能不会再处理 Issue，而是转为内部小范围公开插件，如果感兴趣，你在思源三群、思源装修折腾群、链滴里联系我。
